export const personalData = {
        experiences: [
            {
                id: 1,
                position: 'Web Developer',
                status: 'Internship',
                companyName: 'PT Sultan Langit Teknologi Nusantara',
                companyLink: 'https://www.linkedin.com/company/ptsltn/',
                startDate: 'Jan 2023',
                endDate: 'Apr 2023',
                techStack: ["PHP", "Wordpress", "Bootstrap"],
            },
            {
                id: 2,
                position: 'Fullstack Programmer',
                status: 'Internship',
                companyName: 'Infaq Management Agency',
                companyLink: '',
                startDate: 'Feb 2024',
                endDate: 'Jun 2024',
                techStack: ["Laravel", "React.JS", "CodeIgniter", "MySQL"],
            },
            {
                id: 3,
                position: 'IT Support',
                status: 'Internship',
                companyName: 'PT Kadar Baru Berkah',
                companyLink: '',
                startDate: 'Dec 2023',
                endDate: 'Dec 2024',
                techStack: ["PHP", "Javascript", "JQuery", "MySQL", "Bootstrap"],
            },            
        ],
        skills: {
            frameworks: [
                {
                    id: 1,
                    image: 'https://www.dropbox.com/scl/fi/5u8meb8mghnkbvucx1cui/laravel.webp?rlkey=54lyn9udrvi4xwn75aklcs40v&e=5&st=ac59uzkd&raw=1',
                    name: 'Laravel',
                    width: '70',
                    height: '60',
                },
                {
                    id: 2,
                    image: 'https://www.dropbox.com/scl/fi/j16x05kx6llxes6gmebi0/react.webp?rlkey=iobv7h44hwdclrkm4zj3e4cgf&st=0vw2yu00&raw=1',
                    name: 'React.JS',
                    width: '70',
                    height: '60',
                },
                {
                    id: 3,
                    image: 'https://www.dropbox.com/scl/fi/h5os8rhqujyn6vphyr2r9/express.webp?rlkey=8shhjkkm9umo40sugern7qydb&st=lbtmwknd&raw=1',
                    name: 'Express.JS',
                    width: '70',
                    height: '60',
                },
                {
                    id: 4,
                    image: 'https://www.dropbox.com/scl/fi/v43ifptg26hxki8gbyvxb/spring.webp?rlkey=w1fv6ukithwk748j7x5rd01cz&st=4dm3haun&raw=1',
                    name: 'Spring Boot',
                    width: '70',
                    height: '60',
                },
                {
                    id: 5,
                    image: 'https://www.dropbox.com/scl/fi/j87k7fbfrkaourfvjxtko/codeigniter.webp?rlkey=e0guqxztfthqjigd0t1tuyoou&st=qj89pcrw&raw=1',
                    name: 'CodeIgniter',
                    width: '60',
                    height: '60',
                }
            ],
            programmingLanguage: [
                {
                    id: 1,
                    image: 'https://www.dropbox.com/scl/fi/yuo2b2bal4izmumfppea9/js.webp?rlkey=um9qsf8t95826x2zhvrzy6ret&st=0m63yvvi&raw=1',
                    name: 'Javascript',
                    width: '60',
                    height: '40',
                },
                {
                    id: 2,
                    image: 'https://www.dropbox.com/scl/fi/mvt9tc53aj38vt5fplf7b/php.webp?rlkey=0oqlli550zho1k2dsr73ha63t&st=jk72i5sp&raw=1',
                    name: 'PHP',
                    width: '100',
                    height: '40',
                },
                {
                    id: 3,
                    image: 'https://www.dropbox.com/scl/fi/8vsy7rz7qcczw5ckipzlb/java.webp?rlkey=bt9srtoojwlw7w4dql7cet23f&st=6uz8psrb&raw=1',
                    name: 'Java',
                    width: '40',
                    height: '60',
                },
                {
                    id: 4,
                    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Go_Logo_Blue.svg/1200px-Go_Logo_Blue.svg.png',
                    name: 'Go',
                    width: '150',
                    height: '150',
                }
            ],
            databases: [
                {
                    id: 1,
                    image: 'https://www.dropbox.com/scl/fi/hv1lni1dr6opubfxv2a0t/mysql.webp?rlkey=0z85vg4wtkivl7swpvqpkursr&st=6ylratei&raw=1',
                    name: 'MySQL',
                    width: '100',
                    height: '40',
                },
                {
                    id: 2,
                    image: 'https://www.dropbox.com/scl/fi/ulujv6ldejb6pxw2dnt8v/postgresql.webp?rlkey=d99cre1ilngirl58unlfn7irw&st=gcfbovkk&raw=1',
                    name: 'PostgreSQL',
                    width: '60',
                    height: '40',
                },
                {
                    id: 3,
                    image: 'https://www.dropbox.com/scl/fi/8z32mc8h4kdf0iu58ju5c/mongodb.webp?rlkey=zvj6q9058ggqeomsp2z76s43q&st=5vhgfky2&raw=1',
                    name: 'MongoDB',
                    width: '40',
                    height: '60',
                }
            ],
            other: [
                {
                    id: 1,
                    image: 'https://www.dropbox.com/scl/fi/7a6f0ukrm1fordem3vv0l/git.webp?rlkey=ndsw5ryvy1ptd67hgis63klmi&st=qgyoifg5&raw=1',
                    name: 'Git',
                    width: '70',
                    height: '50',
                },
                {
                    id: 2,
                    image: 'https://www.dropbox.com/scl/fi/jqn8ij0y4jof0zqhqf9iv/postmanapi.webp?rlkey=jq1bpmp7waj6cdvgtnsm1ovwu&st=v7p0bi05&raw=1',
                    name: 'Postman API',
                    width: '70',
                    height: '50',
                },
                {
                    id: 3,
                    image: 'https://www.dropbox.com/scl/fi/jlgfuzdir6gd04iiqbmic/node.webp?rlkey=0ybt4myin5ebxuu3wd5if3ees&st=ul7l8g81&raw=1',
                    name: 'Node.JS',
                    width: '60',
                    height: '60',
                },
                {
                    id: 4,
                    image: 'https://www.dropbox.com/scl/fi/l2byqx76ohp2bc3vdpqoc/docker.webp?rlkey=wcabtldy4f53q2ys7g79jzqfv&st=dgn2yl0l&raw=1',
                    name: 'Docker',
                    width: '60',
                    height: '60',
                },
                {
                    id: 5,
                    image: 'https://www.dropbox.com/scl/fi/gv1mnlv0bvidup0q0phih/gcp.webp?rlkey=yb8oc5sdakqyjlun9h3crd2l7&st=djjmcnlt&raw=1',
                    name: 'Google Cloud Platform',
                    width: '80',
                    height: '60',
                },
            ],
        },
        educations: [
            {
                id: 1,
                companyName: '',
                companyLink: '',
                companyPlace: '',
                startDate: '',
                endDate: '',
                description: [],
                techStack: [],
            },
        ],
        projects: [
            {
                id: 1,
                image: 'https://dl.dropboxusercontent.com/scl/fi/0niqiy1zmye988x7derxp/sltn_page.webp?rlkey=37r3pgi9esno9ii6exy4uwgu9&st=qz2x5whi&dl=1',
                title: 'Job Portal Wordpress Theme',
                link: '',
                description: 'Tema WordPress untuk portal lowongan kerja di PT Sultan Langit Teknologi Nusantara, menggunakan HTML, CSS, JS, PHP, dan Bootstrap. Memudahkan pencari kerja menemukan lowongan sesuai kriteria.',
                techStack: ['PHP', 'Wordpress', 'Bootstrap'],
                linkGithub: 'https://github.com/myfirnanda/magang-SLTN_web-job-portal',
                linkPreview: '',
            },
            {
                id: 2,
                image: 'https://dl.dropboxusercontent.com/scl/fi/7vlr300y2p0icnzfo5xf1/simenta_TaskList.webp?rlkey=gia5gs8v3qnr49hv4x8ak9dtd&st=vedntlbk&dl=1',
                title: 'SIMENTA - Task Management App',
                link: '',
                description: 'Sistem manajemen tugas untuk mahasiswa, dibangun dengan Node.js, Express.js, Sequelize.js, MySQL, dan Bootstrap. Memudahkan pengelolaan, pelacakan, dan pemantauan tugas akademik.',
                techStack: ['Node.JS', 'Sequelize.JS', 'MySQL', 'Bootstrap'],
                linkGithub: 'https://github.com/myfirnanda/magang-SLTN_web-job-portal',
                linkPreview: '',
            },
            {
                id: 4,
                image: 'https://dl.dropboxusercontent.com/scl/fi/gkqh0l41ohook0di40ub4/1687679763706.jpg?rlkey=vc96v6fr9o6ezkcdae5do4hmc&st=rs1vnyew&dl=1',
                title: 'SIPINKU - Book Loan Application',
                link: '',
                description: 'Aplikasi web peminjaman buku berbasis Node.js dan MongoDB. Fitur mencakup registrasi, autentikasi, manajemen buku, sewa & pengembalian, denda keterlambatan, serta pengelolaan peran admin dan pengguna.',
                techStack: ['Node.JS', 'MongoDB', 'EJS'],
                linkGithub: '',
                linkPreview: '',
            },
            {
                id: 5,
                image: 'https://dl.dropboxusercontent.com/scl/fi/7q0jdi8zioob36n552gsx/eatwise_1712848245564-1.jpg?rlkey=7gqnooo0lib2wvb9j9nz1m09f&st=gs5j8ulb&dl=1',
                title: 'Eatwise - Vegan Diet Journal & Recipe Explorer App',
                link: '',
                description: 'Aplikasi mobile untuk mengatasi obesitas di Indonesia, fokus pada pola makan vegan dan mindful eating. Fitur unggulan: deteksi bahan dari gambar, rekomendasi resep vegan personal, pelacakan kalori, dan edukasi gaya hidup sehat.',
                techStack: ['Node.JS', 'Sequelize.JS', 'GCP', 'MySQL'],
                linkGithub: '',
                linkPreview: '',
            },
            {
                id: 6,
                image: 'https://dl.dropboxusercontent.com/scl/fi/wkiwomdw6e9i2l2tqpkvq/lmi_1723005715434.webp?rlkey=h6570wu3tyvuua44kycp6i1rq&st=vq7a3q7g&dl=1',
                title: 'LMI Blog & CMS Dashboard',
                link: '',
                description: 'Website informasi dan artikel kegiatan LMI dengan dashboard CMS untuk kelola konten (buat, edit, publikasi). Backend pakai Laravel, frontend React, dilengkapi fitur keamanan dan optimasi performa untuk pengalaman pengguna yang lancar dan aman.',
                techStack: ['Laravel', 'React.JS', 'MySQL', 'TailwindCSS'],
                linkGithub: '',
                linkPreview: '',
            },
        ],
        certificates: [
            {
                id: 1,
                image: 'https://www.dropbox.com/scl/fi/6pewsutusz2ezx3nbl9vs/cloud-engineer.webp?rlkey=p9gcssqxelcme8gfofmeuok80&st=qedxkm1a&raw=1',
                title: 'Becoming Cloud Engineer',
                source: 'Dicoding Indonesia',
                link: 'https://www.dicoding.com/certificates/123456',
            },
            {
                id: 2,
                image: 'https://dl.dropboxusercontent.com/scl/fi/cwc7vgfdjxsawihzxblsu/backend.webp?rlkey=l57qnb39ouvigi04xbm4s5o75&st=x1in8y3s&dl=1',
                title: 'Backend Developer',
                source: 'Dicoding Indonesia',
                link: 'https://www.dicoding.com/certificates/123456',
            },
            {
                id: 3,
                image: 'https://www.dropbox.com/scl/fi/2vszy4wwzxh9rtiriebav/frontend.webp?rlkey=qograise5vpj7kbzrrtyosxi5&st=9dntkze8&raw=1',
                title: 'Frontend Developer',
                source: 'Dicoding Indonesia',
                link: 'https://www.dicoding.com/certificates/123456',
            },
            {
                id: 4,
                image: 'https://dl.dropboxusercontent.com/scl/fi/rlkyt7g4qhfklwoota4xd/react.webp?rlkey=9ttjgyc5y7bue5iuy5z9ata9r&st=0ifsxt75&dl=1',
                title: 'Learn Making React.JS App',
                source: 'Dicoding Indonesia',
                link: 'https://www.dicoding.com/certificates/123456',
            },
            {
                id: 5,
                image: 'https://dl.dropboxusercontent.com/scl/fi/gveup42at66cyqnrptzjg/js.webp?rlkey=epoehtsvd86or95smlep687pc&st=et4xygo5&dl=1',
                title: 'Learn Javascript',
                source: 'Dicoding Indonesia',
                link: 'https://www.dicoding.com/certificates/123456',
            },
            {
                id: 6,
                image: 'https://dl.dropboxusercontent.com/scl/fi/t0bnan07rvb29zbd6sql3/software-dev.webp?rlkey=c3s96vvpyzyi83kz7qww13zsl&st=dw5xgjsd&dl=1',
                title: 'Software Developer',
                source: 'Dicoding Indonesia',
                link: 'https://www.dicoding.com/certificates/123456',
            },
        ],
};